# Generated by Django 3.1 on 2020-08-27 10:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Page',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='name',
            new_name='project_name',
        ),
        migrations.AddField(
            model_name='project',
            name='update_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last Updated'),
            preserve_default=False,
        ),
    ]
