# Generated by Django 3.1 on 2020-08-27 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20200827_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('permalink', models.CharField(max_length=12, unique=True)),
                ('update_date', models.DateTimeField(verbose_name='Last Updated')),
                ('bodytext', models.TextField(blank=True, verbose_name='Page Content')),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_to_server', models.CharField(max_length=9600)),
                ('msg_from_server', models.CharField(max_length=9600)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='gps_reading',
        ),
        migrations.RemoveField(
            model_name='project',
            name='gyro_reading',
        ),
        migrations.RemoveField(
            model_name='project',
            name='ir_reading',
        ),
        migrations.RemoveField(
            model_name='project',
            name='lcd_msg',
        ),
        migrations.RemoveField(
            model_name='project',
            name='server_rx',
        ),
        migrations.RemoveField(
            model_name='project',
            name='server_tx',
        ),
        migrations.RemoveField(
            model_name='project',
            name='sonar_reading',
        ),
    ]
