# Generated by Django 3.1 on 2020-08-27 22:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20200827_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='permalink',
            field=models.CharField(default=django.utils.timezone.now, max_length=32, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='server',
            name='server_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=64, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='server',
            name='update_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last Updated'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='server',
            name='msg_from_server',
            field=models.CharField(blank=True, max_length=9600),
        ),
        migrations.AlterField(
            model_name='server',
            name='msg_to_server',
            field=models.CharField(blank=True, max_length=9600),
        ),
    ]
