# Generated by Django 3.1 on 2020-08-27 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20200828_0111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensors_name', models.CharField(max_length=64, unique=True)),
                ('permalink', models.CharField(max_length=32, unique=True)),
                ('update_date', models.DateTimeField(verbose_name='Last Updated')),
                ('lcd_msg', models.CharField(blank=True, max_length=64)),
                ('sonar_reading', models.FloatField(blank=True, max_length=64)),
                ('gps_reading', models.FloatField(blank=True, max_length=64)),
                ('ir_reading', models.FloatField(blank=True, max_length=64)),
                ('gyro_reading', models.FloatField(blank=True, max_length=64)),
            ],
        ),
    ]
