# Generated by Django 3.1 on 2020-08-27 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_sensors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensors',
            name='gps_reading',
            field=models.FloatField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='sensors',
            name='gyro_reading',
            field=models.FloatField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='sensors',
            name='ir_reading',
            field=models.FloatField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='sensors',
            name='lcd_msg',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='sensors',
            name='sonar_reading',
            field=models.FloatField(blank=True, max_length=64, null=True),
        ),
    ]
