# Generated by Django 3.1 on 2020-08-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20200828_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensors',
            name='led_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sensors',
            name='led_2',
            field=models.BooleanField(default=False),
        ),
    ]
