# Generated by Django 3.1 on 2020-08-28 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_auto_20200828_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='msg_from_server',
            field=models.CharField(blank=True, default=None, max_length=9600),
        ),
        migrations.AlterField(
            model_name='server',
            name='msg_to_server',
            field=models.CharField(blank=True, default=None, max_length=9600),
        ),
    ]
