# Generated by Django 3.1 on 2020-08-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_auto_20200828_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_name', models.CharField(max_length=64, unique=True)),
                ('permalink', models.CharField(max_length=32, unique=True)),
                ('update_date', models.DateTimeField(verbose_name='Last Updated')),
                ('ac', models.BooleanField(default=False)),
                ('irobot', models.BooleanField(default=False)),
            ],
        ),
    ]
