# Generated by Django 3.1 on 2020-08-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_home'),
    ]

    operations = [
        migrations.CreateModel(
            name='Helicopter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('helicopter_name', models.CharField(max_length=64, unique=True)),
                ('permalink', models.CharField(max_length=32, unique=True)),
                ('update_date', models.DateTimeField(verbose_name='Last Updated')),
            ],
        ),
    ]
