# Generated by Django 3.1 on 2020-08-28 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_helicopter'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Page',
            new_name='Page_Geneal',
        ),
        migrations.RenameModel(
            old_name='Project',
            new_name='Page_Project',
        ),
    ]
