# Generated by Django 3.1 on 2020-08-28 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_auto_20200828_1942'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sensors',
            new_name='Sensors_Set',
        ),
    ]
