# Generated by Django 3.1 on 2020-08-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_auto_20200828_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='page_project',
            name='bodytext',
            field=models.TextField(blank=True, verbose_name='Page Content'),
        ),
    ]
