# Generated by Django 3.1 on 2020-08-29 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_page_project_bodytext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page_project',
            name='bodytext',
        ),
    ]
