# Generated by Django 3.1 on 2020-08-29 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_remove_page_project_bodytext'),
    ]

    operations = [
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_functionality', models.CharField(max_length=64)),
                ('functions', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='page_project',
            name='functionality',
        ),
        migrations.AddField(
            model_name='page_project',
            name='functionality',
            field=models.ManyToManyField(to='pages.Function'),
        ),
    ]
