# Generated by Django 3.1 on 2020-08-29 13:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_remove_function_project_functionality'),
    ]

    operations = [
        migrations.AddField(
            model_name='function',
            name='project_functionality',
            field=models.CharField(default=django.utils.timezone.now, max_length=64),
            preserve_default=False,
        ),
    ]
