# Generated by Django 3.1 on 2020-08-29 13:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_function_project_functionality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page_project',
            name='functionality',
        ),
        migrations.AddField(
            model_name='page_project',
            name='functionality',
            field=models.CharField(default=django.utils.timezone.now, max_length=1023),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Function',
        ),
    ]
