# Generated by Django 3.1 on 2020-08-29 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_auto_20200829_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page_project',
            name='functionality',
            field=models.TextField(blank=True),
        ),
    ]
