# Generated by Django 3.1 on 2020-09-12 17:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0024_auto_20200829_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='msg_from_server',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=9600),
            preserve_default=False,
        ),
    ]
