# Generated by Django 3.1 on 2020-09-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_auto_20200912_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='page_project',
            name='limitation',
            field=models.TextField(blank=True),
        ),
    ]
